name: Zoe
on:
  push:
    branches:
      - v1.0
  pull_request:
jobs:
  build:
    name: Building a success workflow
    if: ${{ startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL'
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
             username: ${{secrets.DOCKERHUB_USERNAME}}
             password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: eyjafialla/app:${{ github.sha }}

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          TAGS: eyjafialla/app:${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Send the 'success' notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_TITLE: "Image build and signed"
            SLACK_MESSAGE: |
              Name: Zoe
              Matriculation: A0285964J
              Email: e1221776@u.nus.edu
              GitHub: https://github.com/repo/code.git
              Docker: https://hub.docker.com/repository/docker/username/repo/general
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
 

  jobs2:
    name: Building a fail workflow
    if: ${{ startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' 
          severity: 'HIGH'
          format: 'table'
          output: 'report.txt'

      - name: Send the 'fail' notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_COLOR: '#FF0000'
            SLACK_TITLE: "Scan failed - Zoe"
            SLACK_MESSAGE: |
              The trivy scan has failed, please see uploaded report for details
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  
            
      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'report.txt'
          initial_comment: 'Scan report by Zoe'
            # thread_ts: 'option'

